# -*- coding: utf-8 -*-
"""DataStrcture.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kHfRcnlZ_uczjMIxSTzs5qz_JCeaDMaG
"""

import requests
import urllib.parse

class Solution:
    SWAPI_BASE_URL = "https://challenges.hackajob.co/swapi/api/"

    def fetch_data(self, url):
        response = requests.get(url)
        if response.status_code == 200:
            return response.json()
        return None

    def get_films_and_characters(self, film, character):
        films = self.fetch_data(self.SWAPI_BASE_URL + f"films/?search={urllib.parse.quote(film)}")
        characters = self.fetch_data(self.SWAPI_BASE_URL + f"people/?search={urllib.parse.quote(character)}")

        if films and characters:
            film_titles = []
            character_names = []

            for film_result in films['results']:
                film_title = film_result['title']
                for character_result in characters['results']:
                    character_name = character_result['name']
                    if character_name in [char.split('/')[-2] for char in film_result['characters']]:
                        film_titles.append(film_title)
                for char_url in character_result['films']:
                    film_name = self.fetch_data(char_url)['title']
                    if film_name == film:
                        character_names.append(character_name)

            film_titles.sort()
            character_names.sort()

            return film_titles, character_names

        return None, None

    def run(self, film, character):
        film_titles, character_names = self.get_films_and_characters(film, character)

        if film_titles is not None and character_names is not None:
            films_and_characters = f"{film}: {', '.join(sorted(character_names))}; {character}: {', '.join(sorted(film_titles))}"
            return films_and_characters
        else:
            return None

# Example usage
solution = Solution()
print(solution.run("A New Hope", "Raymus Antilles"))